# Generated by Django 5.0.4 on 2024-04-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_county_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vintage',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
    ]
